name: Update Download Counter

on:
  workflow_dispatch:
    inputs:
      slug:
        description: 'Cursor slug to update'
        required: true
      count:
        description: 'New count value'
        required: true
        type: number

jobs:
  update-counter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Update counter
        run: |
          # Read current counters
          COUNTERS=$(cat data/counters.json)
          
          # Update the specific counter
          UPDATED_COUNTERS=$(echo "$COUNTERS" | jq --arg slug "${{ github.event.inputs.slug }}" --arg count "${{ github.event.inputs.count }}" '.[$slug] = ($count | tonumber)')
          
          # Write back to file
          echo "$UPDATED_COUNTERS" > data/counters.json
          
          # Configure git
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
          # Commit and push
          git add data/counters.json
          git commit -m "Update download count for ${{ github.event.inputs.slug }} to ${{ github.event.inputs.count }}"
          git push 